# image:
#   - Visual Studio 2017 # contains python2.7 ~ python3.8 and mysql 5.7
#   - Visual Studio 2022 # contains python3.7 ~ python3.12 and mysql 8.0

# services: # mysql is now MySQL5.7 now for MySQL8.0
#   - mysql
init:
  - ps: |
      if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2022")
      {
        Start-Service MySQL80
      }
      else
      {
        Start-Service MySQL57
      }


environment:

  matrix:

    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python
    # The list here is complete (excluding Python 2.6, which
    # isn't covered by this document) at the time of writing.
  - TOXENV: "pep8"
    PYTHON: "C:\\Python38-x64"
    DISTUTILS_USE_SDK: "1"
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

  # - TOXENV: "py27"
  #   PYTHON: "C:\\Python27-x64"
  #   DISTUTILS_USE_SDK: "1"
  # - TOXENV: "py35"
  #   PYTHON: "C:\\Python35-x64"
  #   DISTUTILS_USE_SDK: "1"
  #   APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

  # - TOXENV: "py36"
  #   PYTHON: "C:\\Python36-x64"
  #   DISTUTILS_USE_SDK: "1"
  #   APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  # - TOXENV: "py37"
  #   PYTHON: "C:\\Python37-x64"
  #   DISTUTILS_USE_SDK: "1"
  #   APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  - TOXENV: "py38"
    PYTHON: "C:\\Python38-x64"
    DISTUTILS_USE_SDK: "1"
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  - TOXENV: "py39"
    PYTHON: "C:\\Python39-x64"
    DISTUTILS_USE_SDK: "1"
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
  - TOXENV: "py310"
    PYTHON: "C:\\Python310-x64"
    DISTUTILS_USE_SDK: "1"
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
  - TOXENV: "py311"
    PYTHON: "C:\\Python311-x64"
    DISTUTILS_USE_SDK: "1"
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
  - TOXENV: "py312"
    PYTHON: "C:\\Python312-x64"
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    DISTUTILS_USE_SDK: "1"
  - TOXENV: "cover"
    PYTHON: "C:\\Python38-x64"
    DISTUTILS_USE_SDK: "1"
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

install:
  # We need wheel installed to build wheels
  - "%PYTHON%\\python.exe -m pip install tox"

build: false

test_script:
  # Put your test command here.
  # If you don't need to build C extensions on 64-bit Python 3.3 or 3.4,
  # you can remove "build.cmd" from the front of the command, as it's
  # only needed to support those cases.
  # Note that you must use the environment variable %PYTHON% to refer to
  # the interpreter you're using - Appveyor does not do anything special
  # to put the Python evrsion you want to use on PATH.
  - ps: |
      if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2017")
      {
        $env:MYSQL_PWD="Password12!"
        $cmd = '"C:\Program Files\MySQL\MySQL Server 5.7\bin\mysql" -e "create database testqueue;" --user=root'
        iex "& $cmd"
      }
      else
      {
        $env:MYSQL_PWD="Password12!"
        $cmd = '"C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql" -e "create database testqueue;" --user=root'
        iex "& $cmd"
      }

  - |
    echo image: %APPVEYOR_BUILD_WORKER_IMAGE%, tox:%TOXENV%
    "%PYTHON%\\Scripts\\tox.exe"

#on_success:
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your wheels from the Appveyor "artifacts" tab for your build.
