version: 2.1
jobs:
  py27:
    docker:
      # Primary container image where all steps run.
      - image: circleci/python:2.7.17
        environment:
          TOXENV: py27
      # MySQL env for mysql queue tests
      - image: circleci/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: testqueue
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd
          MYSQL_HOST: '%'

    steps: &common_steps
      - checkout
      - run:
          # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 5
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          command: |
            pip install tox
      - run:
          command: | # tell the operating system to remove the file size limit on core dump files
            tox
      - run: bash <(curl -s https://codecov.io/bash) -cF python
      - run:
          command: |
            mkdir -p /tmp/core_dumps
            ls core.* && cp core.* /tmp/core_dumps
          when: on_fail
      - store_artifacts:
          # collect core dumps
          path: /tmp/core_dumps
      - store_artifacts:
          path: .coverage
      - store_artifacts:
          path: coverage.xml
      - store_artifacts:
          path: htmlcov

  py38:
    docker:
      # Primary container image where all steps run.
      - image: cimg/python:3.8
        environment:
          TOXENV: py38
      # MySQL env for mysql queue tests
      - image: circleci/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: testqueue
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd
    steps: *common_steps
  py39:
    docker:
      # Primary container image where all steps run.
      - image: cimg/python:3.9
        environment:
          TOXENV: py39
      # MySQL env for mysql queue tests
      - image: circleci/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: testqueue
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd
    steps: *common_steps
  py310:
    docker:
      # Primary container image where all steps run.
      - image: cimg/python:3.10
        environment:
          TOXENV: py310
      # MySQL env for mysql queue tests
      - image: circleci/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: testqueue
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd
    steps: *common_steps
  py311:
    docker:
      # Primary container image where all steps run.
      - image: cimg/python:3.11
        environment:
          TOXENV: py311
      # MySQL env for mysql queue tests
      - image: circleci/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: testqueue
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd
    steps: *common_steps
  py312:
    docker:
      # Primary container image where all steps run.
      - image: cimg/python:3.12
        environment:
          TOXENV: py312
      # MySQL env for mysql queue tests
      - image: circleci/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: testqueue
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd
    steps: *common_steps

  pep8:
    docker:
      # Primary container image where all steps run.
      - image: cimg/python:3.8
        environment:
          TOXENV: pep8
      # MySQL env for mysql queue tests
      - image: circleci/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: testqueue
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd
    steps: *common_steps


  cover:
    docker:
      # Primary container image where all steps run.
      - image: cimg/python:3.8
        environment:
          TOXENV: cover
      # MySQL env for mysql queue tests
      - image: circleci/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: testqueue
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd
    steps: *common_steps

workflows:
  version: 2
  build:
    jobs:
      - pep8
      - py38
      - py39
      - py310
      - py311
      - py312
      - cover
